version: "3.7"
services:
  tcpsrv:
    build: .
    image: tcpsrv:v1
    deploy:
      replicas: 3 
      resources:
        limits:
          cpus: "0.1"
          memory: 20M
    ports:
      - "31315:31315"
